# yfinance 패키지를 사용한 주식 정보 확인

In [2]:
import yfinance as yf

기업별 고유 티커 기호

| Compnay | Ticker |
|:--:|:--:|
| 삼성전자 | 005930.KS |
| 하이닉스 | 000660.KS |
| 구글 | GOOGL |
| 메타 | META |
| 마이크로소프트 | MSFT |

In [5]:
samsung = yf.Ticker('005930.KS')

In [6]:
print(type(samsung))  #> Ticker 클래스 객체

<class 'yfinance.ticker.Ticker'>

In [ ]:
samsung.info

{'address1': '129, Samsung-ro',
 'address2': 'Yeongtong-gu',
 'city': 'Suwon-si',
 'zip': '16677',
 'country': 'South Korea',
 'phone': '82 10 3060 0730',
 'fax': '82 3 1200 7538',
 'website': 'https://www.samsung.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Samsung Electronics Co., Ltd. engages in the consumer electronics, information technology and mobile communications, and device solutions businesses worldwide. The company operates through four divisions: Device eXperience (DX), Device Solutions (DS), SDC, and Harman. The company offers smartphones, tablets, audio sounds, watches, switches, and accessories; TVs, and sound devices; appliances, including refrigerators, washing machines and dryers, vacuum cleaners, cooking appliances, dishwashers, air conditioners, and air purifiers; monitors and memory storage products; displays, and smart and LED signages; and other accessories. It also engages in venture capital investments, cloud services, network devices installation, semiconductor equipment services, digital advertising platforms, marketing, consulting, connected services provider, logistics, financing, and software design activities. In addition, the company provides toll processing and sales of semiconductors and display panels; development and sale of network solutions; manufacture of semiconductors and food; the provision of repair services for electronic devices; and development and supply of semiconductor process defect and quality control software, as well as digital televisions, foundry, system large scale integration (LSI). Further, it provides connected car systems, audio and visual products, enterprise automation solutions, and connected services. Samsung Electronics Co., Ltd. was incorporated in 1969 and is based in Suwon-si, South Korea.',
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Tae-Moon  Roh Ph.D.',
   'age': 57,
   'title': 'CEO, Head of Mobile eXperience & Head of Device eXperience Division and Exec Director',
   'yearBorn': 1968,
   'fiscalYear': 2024,
   'totalPay': 5099000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hark-Kyu  Park',
   'age': 61,
   'title': 'President & Head of Corporate Management Office at DX Division',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 3346000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Si-young  Choi',
   'title': 'President & Head of Foundry Business',
   'fiscalYear': 2024,
   'totalPay': 6900000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Young-Hyun  Jun',
   'age': 65,
   'title': 'Vice Chairman, Co-CEO & Head of the Device Solutions Division',
   'yearBorn': 1960,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mauro  Porcini',
   'title': 'President & Chief Design Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hyun-Chong  Kim',
   'title': 'President and Chief Legal Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Kyungwhoon  Cheun',
   'title': 'President',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Soon-Cheol  Park',
   'age': 59,
   'title': 'Executive VP & CFO',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Janghyun  Yoon',
   'title': 'President, CTO of Device eXperience Division & Head of Samsung Research',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Robert M. Yi',
   'title': 'Head of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 1,
 'boardRisk': 1,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1775001600,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 189600.0,
 'open': 192600.0,
 'dayLow': 188600.0,
 'dayHigh': 193600.0,
 'regularMarketPreviousClose': 189600.0,
 'regularMarketOpen': 192600.0,
 'regularMarketDayLow': 188600.0,
 'regularMarketDayHigh': 193600.0,
 'dividendRate': 2264.0,
 'dividendYield': 1.19,
 'exDividendDate': 1766966400,
 'payoutRatio': 0.2526,
 'fiveYearAvgDividendYield': 2.34,
 'beta': 1.121,
 'volume': 7348856,
 'regularMarketVolume': 7348856,
 'averageVolume': 31835578,
 'averageVolume10days': 28117755,
 'averageDailyVolume10Day': 28117755,
 'bid': 190400.0,
 'ask': 190500.0,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 1275036069527552,
 'nonDilutedMarketCap': 1074856334304000,
 'fiftyTwoWeekLow': 52900.0,
 'fiftyTwoWeekHigh': 223000.0,
 'allTimeHigh': 223000.0,
 'allTimeLow': 2420.0,
 'priceToSalesTrailing12Months': 3.8219824,
 'fiftyDayAverage': 178866.0,
 'twoHundredDayAverage': 111762.0,
 'currency': 'KRW',
 'tradeable': False,
 'enterpriseValue': 1168600740134912,
 'forwardPE': 6.6382213,
 'profitMargins': 0.13267,
 'floatShares': 5456638254,
 'sharesOutstanding': 5876745450,
 'heldPercentInsiders': 0.09803,
 'heldPercentInstitutions': 0.47787,
 'impliedSharesOutstanding': 6686083126,
 'lastFiscalYearEnd': 1767139200,
 'nextFiscalYearEnd': 1798675200,
 'mostRecentQuarter': 1767139200,
 'earningsQuarterlyGrowth': 1.554,
 'netIncomeToCommon': 44260954996736,
 'lastSplitFactor': '50:1',
 'lastSplitDate': 1526428800,
 'enterpriseToRevenue': 3.503,
 'enterpriseToEbitda': 13.092,
 '52WeekChange': 1.8435373,
 'SandP52WeekChange': 0.15121746,
 'lastDividendValue': 566.0,
 'lastDividendDate': 1766966400,
 'quoteType': 'EQUITY',
 'currentPrice': 190700.0,
 'targetHighPrice': 340000.0,
 'targetLowPrice': 110000.0,
 'targetMeanPrice': 239873.48,
 'targetMedianPrice': 250000.0,
 'recommendationMean': 1.45946,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 37,
 'totalCash': 125847113564160,
 'totalCashPerShare': 18980.95,
 'ebitda': 89259277025280,
 'totalDebt': 25239138336768,
 'quickRatio': 1.733,
 'currentRatio': 2.328,
 'totalRevenue': 333605947572224,
 'debtToEquity': 5.785,
 'revenuePerShare': 49784.59,
 'returnOnAssets': 0.0504,
 'returnOnEquity': 0.10783,
 'grossProfits': 131370424729600,
 'freeCashflow': 23944373469184,
 'operatingCashflow': 85315146481664,
 'earningsGrowth': 1.622,
 'revenueGrowth': 0.238,
 'grossMargins': 0.39379,
 'ebitdaMargins': 0.26756,
 'operatingMargins': 0.21322,
 'financialCurrency': 'KRW',
 'symbol': '005930.KS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'corporateActions': [],
 'regularMarketTime': 1775091487,
 'exchange': 'KSC',
 'messageBoardId': 'finmb_91868',
 'exchangeTimezoneName': 'Asia/Seoul',
 'exchangeTimezoneShortName': 'KST',
 'gmtOffSetMilliseconds': 32400000,
 'market': 'kr_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 0.5804749,
 'regularMarketPrice': 190700.0,
 'marketState': 'REGULAR',
 'shortName': 'SamsungElec',
 'longName': 'Samsung Electronics Co., Ltd.',
 'averageAnalystRating': '1.5 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 946944000000,
 'regularMarketChange': 1100.0,
 'regularMarketDayRange': '188600.0 - 193600.0',
 'fullExchangeName': 'KSE',
 'averageDailyVolume3Month': 31835578,
 'fiftyTwoWeekLowChange': 137800.0,
 'fiftyTwoWeekLowChangePercent': 2.604915,
 'fiftyTwoWeekRange': '52900.0 - 223000.0',
 'fiftyTwoWeekHighChange': -32300.0,
 'fiftyTwoWeekHighChangePercent': -0.14484304,
 'fiftyTwoWeekChangePercent': 184.35373,
 'earningsTimestamp': 1769580000,
 'earningsTimestampStart': 1777356000,
 'earningsTimestampEnd': 1777356000,
 'earningsCallTimestampStart': 1769648400,
 'earningsCallTimestampEnd': 1769648400,
 'isEarningsDateEstimate': False,
 'epsCurrentYear': 24987.16,
 'priceEpsCurrentYear': 7.63192,
 'fiftyDayAverageChange': 11834.0,
 'fiftyDayAverageChangePercent': 0.06616126,
 'twoHundredDayAverageChange': 78938.0,
 'twoHundredDayAverageChangePercent': 0.7063045,
 'sourceInterval': 20,
 'exchangeDataDelayedBy': 20,
 'trailingPegRatio': 0.1611}

In [8]:
samsung.info.keys()

dict_keys(['address1', 'address2', 'city', 'zip', 'country', 'phone', 'fax', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'companyOfficers', 'auditRisk', 'boardRisk', 'compensationRisk', 'shareHolderRightsRisk', 'overallRisk', 'governanceEpochDate', 'compensationAsOfEpochDate', 'executiveTeam', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'marketCap', 'nonDilutedMarketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'allTimeHigh', 'allTimeLow', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'currency', 'tradeable', 'enterpriseValue', 'forwardPE', 'profitMargins', 'floatShares', 'sharesOutstanding', 'heldPercentInsiders', 'heldPercentInstitutions', 'impliedSharesOutstanding', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'quoteType', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins', 'financialCurrency', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName', 'triggerable', 'customPriceAlertConfidence', 'corporateActions', 'regularMarketTime', 'exchange', 'messageBoardId', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market', 'esgPopulated', 'regularMarketChangePercent', 'regularMarketPrice', 'marketState', 'shortName', 'longName', 'averageAnalystRating', 'cryptoTradeable', 'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'regularMarketChange', 'regularMarketDayRange', 'fullExchangeName', 'averageDailyVolume3Month', 'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 'earningsTimestamp', 'earningsTimestampStart', 'earningsTimestampEnd', 'earningsCallTimestampStart', 'earningsCallTimestampEnd', 'isEarningsDateEstimate', 'epsCurrentYear', 'priceEpsCurrentYear', 'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy', 'trailingPegRatio'])

In [9]:
# Ticker.history(): 주가 데이터
# period 파라미터: 주가를 검색할 기간. (예) '5d': 5일간, '1mo': 1개월간, '1y': 1년간
history_5d = samsung.history('5d')

In [10]:
type(history_5d)  #> DataFrame

pandas.core.frame.DataFrame

In [11]:
history_5d

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-27 00:00:00+09:00,172100.0,181700.0,172000.0,180100.0,29138966,0.0,0.0
2026-03-30 00:00:00+09:00,171000.0,176650.0,170600.0,176300.0,22269147,0.0,0.0
2026-03-31 00:00:00+09:00,170000.0,174700.0,167000.0,167200.0,38659593,0.0,0.0
2026-04-01 00:00:00+09:00,179000.0,190800.0,178000.0,189650.0,32390251,0.0,0.0
2026-04-02 00:00:00+09:00,192600.0,193600.0,183000.0,183500.0,13071953,0.0,0.0

In [ ]:
samsung.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-03 00:00:00+09:00,209500.0,212500.0,195100.0,195100.0,54879010,0.0,0.0
2026-03-04 00:00:00+09:00,184200.0,195900.0,171900.0,172200.0,89427954,0.0,0.0
2026-03-05 00:00:00+09:00,195000.0,199700.0,188100.0,191600.0,53959129,0.0,0.0
2026-03-06 00:00:00+09:00,186100.0,189700.0,181000.0,188200.0,29522650,0.0,0.0
2026-03-09 00:00:00+09:00,173500.0,175500.0,167300.0,173500.0,43066020,0.0,0.0
2026-03-10 00:00:00+09:00,187600.0,191500.0,184300.0,187900.0,33530170,0.0,0.0
2026-03-11 00:00:00+09:00,193000.0,194800.0,187700.0,190000.0,24311356,0.0,0.0
2026-03-12 00:00:00+09:00,186600.0,190000.0,185900.0,187900.0,20440753,0.0,0.0
2026-03-13 00:00:00+09:00,180000.0,186200.0,179900.0,183500.0,19566331,0.0,0.0
2026-03-16 00:00:00+09:00,184600.0,189000.0,183600.0,188700.0,19747901,0.0,0.0
2026-03-17 00:00:00+09:00,198000.0,198000.0,193100.0,193900.0,20300082,0.0,0.0
2026-03-18 00:00:00+09:00,200500.0,209000.0,199700.0,208500.0,25148481,0.0,0.0
2026-03-19 00:00:00+09:00,199900.0,205000.0,199600.0,200500.0,19884483,0.0,0.0
2026-03-20 00:00:00+09:00,202000.0,202500.0,199000.0,199400.0,35279762,0.0,0.0
2026-03-23 00:00:00+09:00,190500.0,191200.0,186300.0,186300.0,30268173,0.0,0.0
2026-03-24 00:00:00+09:00,195500.0,196000.0,185500.0,189700.0,25458914,0.0,0.0
2026-03-25 00:00:00+09:00,193700.0,196400.0,189000.0,189000.0,22995904,0.0,0.0
2026-03-26 00:00:00+09:00,185500.0,185900.0,178900.0,180100.0,32074131,0.0,0.0
2026-03-27 00:00:00+09:00,172100.0,181700.0,172000.0,180100.0,29138966,0.0,0.0
2026-03-30 00:00:00+09:00,171000.0,176650.0,170600.0,176300.0,22269147,0.0,0.0
2026-03-31 00:00:00+09:00,170000.0,174700.0,167000.0,167200.0,38659593,0.0,0.0
2026-04-01 00:00:00+09:00,179000.0,190800.0,178000.0,189650.0,32390251,0.0,0.0
2026-04-02 00:00:00+09:00,192600.0,193600.0,180100.0,181400.0,15508595,0.0,0.0

In [14]:
type(samsung.recommendations)

pandas.core.frame.DataFrame

In [ ]:
samsung.recommendations
# 지난 3개월 동안의 애널리스트의 분석(매수/매도 의견)

  period  strongBuy  buy  hold  sell  strongSell
0     0m         12   23     1     0           1
1    -1m         11   23     2     0           0
2    -2m         11   23     2     0           0

In [16]:
hynix = yf.Ticker('000660.KS')

In [17]:
hynix.history(period='5d')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-03-27 00:00:00+09:00,890000.0,934000.0,880000.0,933000.0,4520942,0.0,0.0
2026-03-30 00:00:00+09:00,867000.0,884000.0,862000.0,873000.0,4498502,0.0,0.0
2026-03-31 00:00:00+09:00,817000.0,852000.0,806000.0,807000.0,7194351,0.0,0.0
2026-04-01 00:00:00+09:00,884000.0,905000.0,858000.0,897000.0,6255058,0.0,0.0
2026-04-02 00:00:00+09:00,912000.0,914000.0,847000.0,860000.0,2573495,0.0,0.0

In [ ]:
hynix.recommendations  # 4개월간의 전문가들의 매수/매도 의견

  period  strongBuy  buy  hold  sell  strongSell
0     0m         11   25     2     0           1
1    -1m         10   24     2     0           1
2    -2m         10   24     2     0           1
3    -3m         10   25     1     1           0