# Pandas
*   데이터 분석을 위한 python 라이브러리
*   R보다 Pandas의 학습, 성능, 활용분야 등이 좋음

-   Series와 DataFrame
    *   Series: index와 value로 이루어짐
    *   DataFrame: index, column, value로 이루어짐

## Series

In [1]:
import numpy as np
import pandas as pd

### Series 선언

In [2]:
test = pd.Series(np.random.randint(10, size = 5))
test

0    9
1    6
2    9
3    2
4    9
dtype: int64

In [3]:
test2 = pd.Series({"name": "easyup",
                   "class": "python",
                   "category": "IT"})
test2

name        easyup
class       python
category        IT
dtype: object

In [4]:
test2[0]

/tmp/ipython-input-2543243210.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  test2[0]

'easyup'

In [5]:
test3 = pd.Series({"name": "easyup",
                   "class": "python",
                   "age": 20})
test3

name     easyup
class    python
age          20
dtype: object

In [6]:
type(test3[2])

/tmp/ipython-input-2661810986.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(test3[2])

int

In [7]:
type(test3[0])

/tmp/ipython-input-206449599.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  type(test3[0])

str

### index(행) 이름 설정

In [8]:
test4 = pd.Series(np.random.randint(10, size = 5), index = range(1, 6))
test4

1    8
2    9
3    1
4    3
5    8
dtype: int64

In [9]:
test4[1]

np.int64(8)

In [11]:
test5 = pd.Series(np.random.randint(10, size = 5), index = list('ABCDE'))
test5

A    4
B    2
C    2
D    6
E    5
dtype: int64

In [13]:
test5.index, test5.values

(Index(['A', 'B', 'C', 'D', 'E'], dtype='object'), array([4, 2, 2, 6, 5]))

In [14]:
scalar_test = pd.Series(10, index=range(1, 10))
scalar_test

1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
9    10
dtype: int64

### Series 데이터 선택

In [15]:
test5['A']

np.int64(4)

In [16]:
test5.A

np.int64(4)

### Series Broadcasting

In [17]:
test5

A    4
B    2
C    2
D    6
E    5
dtype: int64

In [18]:
test5 * 100

A    400
B    200
C    200
D    600
E    500
dtype: int64

### Series Indexing

In [19]:
test5[2:]

C    2
D    6
E    5
dtype: int64

In [20]:
test5[::-1]

E    5
D    6
C    2
B    2
A    4
dtype: int64